apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: test-station
  namespace: fleet-local
spec:
  repo: git@github.com:smysnk/test-station-private.git
  clientSecretName: smysnk-com-github-ssh
  branch: staging
  paths:
    - .
