apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-station.ingestName" . }}
  labels:
    {{- include "test-station.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingest
spec:
  type: {{ .Values.ingest.service.type }}
  selector:
    {{- include "test-station.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ingest
  ports:
    - name: http
      port: {{ .Values.ingest.service.port }}
      targetPort: http
