{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "test-station.fullname" . }}-migrate-{{ .Release.Revision }}
  labels:
    {{- include "test-station.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: {{ .Values.migrations.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "test-station.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      restartPolicy: Never
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . | quote }}
        {{- end }}
      {{- end }}
      containers:
        - name: migrate
          image: {{ include "test-station.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["migrate"]
          envFrom:
            - configMapRef:
                name: {{ include "test-station.serverConfigMapName" . }}
            - secretRef:
                name: {{ include "test-station.serverSecretName" . }}
{{- end }}
