apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-station.portalName" . }}
  labels:
    {{- include "test-station.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal
spec:
  replicas: {{ .Values.portal.replicaCount }}
  selector:
    matchLabels:
      {{- include "test-station.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: portal
  template:
    metadata:
      labels:
        {{- include "test-station.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: portal
      annotations:
        {{- toYaml .Values.portal.podAnnotations | nindent 8 }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . | quote }}
        {{- end }}
      {{- end }}
      containers:
        - name: portal
          image: {{ include "test-station.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- toYaml .Values.portal.args | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.portal.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "test-station.portalName" . }}-env
            - secretRef:
                name: {{ include "test-station.portalName" . }}-secret
          livenessProbe:
            httpGet:
              path: {{ .Values.portal.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.portal.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.portal.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.portal.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.portal.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.portal.readinessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.portal.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.portal.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.portal.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.portal.affinity | nindent 8 }}
