apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "test-station.portalName" . }}-env
  labels:
    {{- include "test-station.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal
data:
  PORTAL_PORT: {{ .Values.portal.env.PORTAL_PORT | quote }}
  PORTAL_GRAPHQL_PATH: {{ .Values.portal.env.PORTAL_GRAPHQL_PATH | quote }}
  SERVER_URL: {{ default (printf "http://%s:%v" (include "test-station.serverName" .) .Values.server.service.port) .Values.portal.env.SERVER_URL | quote }}
  NEXTAUTH_URL: {{ .Values.portal.env.NEXTAUTH_URL | quote }}
  PORTAL_DEFAULT_PROJECT_KEYS: {{ .Values.portal.env.PORTAL_DEFAULT_PROJECT_KEYS | quote }}
  PORTAL_ADMIN_EMAILS: {{ .Values.portal.env.PORTAL_ADMIN_EMAILS | quote }}
