{{- if .Values.portal.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "test-station.portalName" . }}
  labels:
    {{- include "test-station.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal
  {{- with .Values.portal.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.portal.ingress.className }}
  ingressClassName: {{ .Values.portal.ingress.className }}
  {{- end }}
  rules:
    {{- range .Values.portal.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "test-station.portalName" $ }}
                port:
                  number: {{ $.Values.portal.service.port }}
          {{- end }}
    {{- end }}
  {{- with .Values.portal.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
