apiVersion: v1
kind: Secret
metadata:
  name: {{ include "test-station.portalName" . }}-secret
  labels:
    {{- include "test-station.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal
type: Opaque
stringData:
  NEXTAUTH_SECRET: {{ .Values.portal.secretEnv.NEXTAUTH_SECRET | quote }}
  GITHUB_CLIENT_ID: {{ .Values.portal.secretEnv.GITHUB_CLIENT_ID | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.portal.secretEnv.GITHUB_CLIENT_SECRET | quote }}
  DISCORD_CLIENT_ID: {{ .Values.portal.secretEnv.DISCORD_CLIENT_ID | quote }}
  DISCORD_CLIENT_SECRET: {{ .Values.portal.secretEnv.DISCORD_CLIENT_SECRET | quote }}
