apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-station.serverName" . }}
  labels:
    {{- include "test-station.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "test-station.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        {{- include "test-station.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: server
      annotations:
        {{- toYaml .Values.server.podAnnotations | nindent 8 }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . | quote }}
        {{- end }}
      {{- end }}
      containers:
        - name: server
          image: {{ include "test-station.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- toYaml .Values.server.args | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.server.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "test-station.serverConfigMapName" . }}
            - secretRef:
                name: {{ include "test-station.serverSecretName" . }}
          livenessProbe:
            httpGet:
              path: {{ .Values.server.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.server.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.server.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.server.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.server.readinessProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.server.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.server.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.server.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.server.affinity | nindent 8 }}
