apiVersion: v1
kind: Secret
metadata:
  name: {{ include "test-station.serverName" . }}-secret
  labels:
    {{- include "test-station.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.server.secretEnv.DATABASE_URL | quote }}
  INGEST_API_KEYS: {{ .Values.server.secretEnv.INGEST_API_KEYS | quote }}
  INGEST_SHARED_KEY: {{ .Values.server.secretEnv.INGEST_SHARED_KEY | quote }}
